"""empty message

Revision ID: 26abd0cc4e08
Revises: 7343ae295d24
Create Date: 2018-01-28 21:44:11.025950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26abd0cc4e08'
down_revision = '7343ae295d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('networks', sa.Column('total_ip', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('networks', 'total_ip')
    # ### end Alembic commands ###
