"""empty message

Revision ID: 5f7a5ddbf7af
Revises: 1d0cc801c49f
Create Date: 2018-01-15 20:24:46.074233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f7a5ddbf7af'
down_revision = '1d0cc801c49f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ips', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('networks', sa.Column('desc', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('networks', 'desc')
    op.drop_column('ips', 'status')
    # ### end Alembic commands ###
