"""empty message

Revision ID: 7343ae295d24
Revises: c9bbcecdff68
Create Date: 2018-01-16 20:26:20.747566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7343ae295d24'
down_revision = 'c9bbcecdff68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('networks', sa.Column('network', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_networks_network'), 'networks', ['network'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_networks_network'), table_name='networks')
    op.drop_column('networks', 'network')
    # ### end Alembic commands ###
