"""empty message

Revision ID: c9bbcecdff68
Revises: 5f7a5ddbf7af
Create Date: 2018-01-16 00:24:14.443504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9bbcecdff68'
down_revision = '5f7a5ddbf7af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('networks', sa.Column('active_ip', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('networks', 'active_ip')
    # ### end Alembic commands ###
