"""empty message

Revision ID: fd2ddfab98d6
Revises: c69d82dbdc36
Create Date: 2017-12-25 03:28:07.119502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd2ddfab98d6'
down_revision = 'c69d82dbdc36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'group_id')
    # ### end Alembic commands ###
